---
- name: Install dependencies.
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: true

- name: Execute shell script install.
  ansible.builtin.shell: |
    curl -fsSL https://tailscale.com/install.sh | sh
  ignore_errors: true
  register: shell_script_result
  when:
    - tailscale_platform == "linux"

- name: Print shell script result when failed.
  ansible.builtin.debug:
    msg: "{{ shell_script_result }}"
  when:
    - shell_script_result is failed

- name: Tailscale set atuh-key.
  ansible.builtin.shell: tailscale up --auth-key {{ tailscale_auth_key }}
  register: tailscale_up_result
  when:
    - tailscale_auth_key != ""

- name: Print tailscale up result when failed.
  ansible.builtin.debug:
    msg: "{{ tailscale_up_result }}"
  when:
    - tailscale_up_result is failed
