---
- name: Converge
  hosts: all
  #become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: lipaysamart.tailscale

  tasks:
    - name: Verify that Go is installed and available in the $PATH.
      command: tailscale version
      changed_when: false
